### ISSUE TITLE
Middle clicking doesn't duplicate tab

### ISSUE THREAD

**Issue by buh6173** [kiheru/firefox-reload-button#1]
Normally in Firefox, middle clicking the reload button should create a duplicate tab. However, currently middle clicking only refreshes the current tab.

**Comment by kiheru** [comment]
Thank you for the bug report (and sorry for the late answer)! It used to be that telling the mouse buttons apart was not possible, but apparently firefox 72 added support for it. Now I finally got to fix a long standing issue. Fixed in latest source.

**Comment by buh6173** [comment]
I just checked. This has not been fixed.

Unless you're saying this is going to be fixed in a later update?

**Comment by kiheru** [comment]
It should work, if you have the latest version. It may take some time to firefox to update the extension (assuming you have autoupdating extensions on). Please check that you have version 0.2 of the extension.

Another reason it might not work for you, is if your Firefox version is too old (according to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/onClicked at least version 72 is required). Admittedly I have tested it only with latest release (on Linux and Windows), because that's what I have on my computers.

**Comment by buh6173** [comment]
Just tested now, seems to be working now.
